DOWNLINK_CODES = {
    'Issues': '63',
    'Mission Lead': '64',
    'Tactical Downlink Lead': '66',
    'Systems': '120',
    'Activity Lead': '122',
    'SAPP': '67',
    'Data Management': '68',
    'Mechanisms': '71',
    'Mobility': '72',
    'Power': '73',
    'SA-SPaH': '74',
    'Telecom': '75',
    'Thermal': '76',
    'Testbed': '154',
    'Localization Scientist': '78',
    'Payload Downlink Coordinator': '106',
    'APXS PDL': '79',
    'ChemCam Eng PDL': '80',
    'ChemCam Science PDL': '118',
    'CheMin PDL': '81',
    'DAN PDL': '82',
    'ECAM PDL': '108',
    'Mastcam PDL': '83',
    'MMM MDM': '160',
    'MAHLI PDL': '84',
    'MARDI PDL': '85',
    'RAD PDL': '86',
    'REMS PDL': '87',
    'SAM PDL': '88',
    'OPGS Pipeline Ops': '89',
    'Ground Data System Analyst': '90',
    'ACE': '91'
}

UPLINK_CODES = {
    'Issues for Next Plan': '38',
    'Sol Scenario': '39',
    'Seq Deviations from Activity Plan': '148',
    'IPE Supra Tactical': '40',
    'Mission Lead': '41',
    'Tactical Uplink Lead': '42',
    'Engineering Uplink Lead': '43',
    'Science Planner': '44',
    'Sequence Integration Engineer': '45',
    'Data Management': '126',
    'Rover Planner': '46',
    'SOWG Chair/SUR': '48',
    'SOWG Documentarian': '49',
    'Long Term Planner': '128',
    'SSS Scientist': '50',
    'Surface Properties Scientist': '51',
    'APXS PUL': '52',
    'ChemCam Eng PUL': '53',
    'ChemCam Science PUL': '116',
    'CheMin PUL': '54',
    'DAN PUL': '55',
    'ECAM PUL': '56',
    'Mastcam PUL': '57',
    'MAHLI PUL': '58',
    'MARDI PUL': '59',
    'MMM MTL': '110',
    'RAD PUL': '60',
    'REMS PUL': '61',
    'SAM PUL': '62'
}

PAGE_TOPIC_URL_STRINGS = {
    'all': 'all',
    'Summary': 'Summary',
    'Engineering Requests': 'Engineering%20Requests',
    'Detailed Report': 'Detailed%20Report',
    'Anomalies and Concerns': 'Anomalies%20and%20Concerns%20%28high-level%20description%2C%20mitigation%20and%20assessment%20results%20only%29',
    'All ITAR/EAR Restricted': 'All%20ITAR%2FEAR%20Restricted',
    'Contacts': 'Contacts',
    'Downlink Assessment': 'Downlink%20Assessment',
    'Power Incons': 'Power%20Incons',
    'Overall Summary': 'Overall%20Summary',
    'EVR Summary': 'EVR%20Summary',
    'Sequence Summary': 'Sequence%20Summary',
    'Temperature Summary': 'Temperature%20Summary',
    'EHA Summary': 'EHA%20Summary',
    'Noteworthy Images': 'Noteworthy%20Images',
    'Autonomous Image Summary': 'Autonomous%20Image%20Summary',
    'Miscellaneous': 'Miscellaneous',
    'Notes to ECAM PUL': 'Notes%20to%20ECAM%20PUL',
    'Consumables': 'Consumables',
    'TLS': 'TLS',
    'GC': 'GC',
    'Consumable': 'Consumable',
    'QMS': 'QMS',
    'Autolook Mosaics': 'Autolook%20Mosaics',
    'Quicklook Mosaics Created': 'Quicklook%20Mosaics%20Created',
    'Terrain Meshes Created': 'Terrain%20Meshes%20Created',
    'Special Products Created': 'Special%20Products%20Created',
    'OPGS Product Locations': 'OPGS%20Product%20Locations',
    'OPGS Product Counts': 'OPGS%20Product%20Counts',
    'OPGS Pipeline Failures': 'OPGS%20Pipeline%20Failures',
    'Notes': 'Notes',
    'Shift Handover/Issues': 'Shift%20Handover%2FIssues',
    'Flight Rules and Command Status': 'Flight%20Rules%20and%20Command%20Status',
    'Condition File Status': 'Condition%20File%20Status',
    'Science Kickoff (ECAM)': 'Science%20Kickoff%20%28ECAM%29',
    'SOWG Meeting (ECAM)': 'SOWG%20Meeting%20%28ECAM%29',
    'Activity Refinement (ECAM)': 'Activity%20Refinement%20%28ECAM%29',
    'Imaging Plan Summary': 'Imaging%20Plan%20Summary',
    'APAM (ECAM)': 'APAM%20%28ECAM%29',
    'Delivered Sequences (ECAM)': 'Delivered%20Sequences%20%28ECAM%29',
    'Master/Submaster Walkthrough (ECAM)': 'Master%2FSubmaster%20Walkthrough%20%28ECAM%29',
    'Sequence Report Walkthrough (ECAM)': 'Sequence%20Report%20Walkthrough%20%28ECAM%29',
    'Data Reprioritization/Retransmission Requests': 'Data%20Reprioritization%2FRetransmission%20Requests',
    'Notes to ECAM PDL': 'Notes%20to%20ECAM%20PDL',
    'Summary PUL1': 'Summary%20PUL1',
    'Summary PUL2': 'Summary%20PUL2',
}

PAGE_TOPIC_FUNCTION_NAMES = {
    'all': 'all',
    'Summary': 'summary',
    'Engineering Requests': 'engineering_requests',
    'Detailed Report': 'detailed_report',
    'Anomalies and Concerns': 'anomalies_and_concerns',
    'All ITAR/EAR Restricted': 'all_itar_ear_restricted',
    'Contacts': 'contacts',
    'Downlink Assessment': 'downlink_assessment',
    'Power Incons': 'power_incons',
    'Overall Summary': 'overall_summary',
    'EVR Summary': 'evr_summary',
    'Sequence Summary': 'sequence_summary',
    'Temperature Summary': 'temperature_summary',
    'EHA Summary': 'eha_summary',
    'Noteworthy Images': 'noteworthy_images',
    'Autonomous Image Summary': 'autonomous_image_summary',
    'Miscellaneous': 'miscellaneous',
    'Notes to ECAM PUL': 'notes_to_ecam_pul',
    'Consumables': 'consumables',
    'TLS': 'tls',
    'GC': 'gc',
    'Consumable': 'consumable',
    'QMS': 'qms',
    'Autolook Mosaics': 'autolook_mosaics',
    'Quicklook Mosaics Created': 'quicklook_mosaics_created',
    'Terrain Meshes Created': 'terrain_meshes_created',
    'Special Products Created': 'special_products_created',
    'OPGS Product Locations': 'opgs_product_locations',
    'OPGS Product Counts': 'opgs_product_counts',
    'OPGS Pipeline Failures': 'opgs_pipeline_failures',
    'Notes': 'notes',
    'Shift Handover/Issues': 'shift_handover_issues',
    'Flight Rules and Command Status': 'flight_rules_and_command_status',
    'Condition File Status': 'condition_file_status',
    'Science Kickoff (ECAM)': 'science_kickoff_ecam',
    'SOWG Meeting (ECAM)': 'sowg_meeting_ecam',
    'Activity Refinement (ECAM)': 'activity_refinement_ecam',
    'Imaging Plan Summary': 'imaging_plan_summary',
    'APAM (ECAM)': 'apam_ecam',
    'Delivered Sequences (ECAM)': 'delivered_sequences_ecam',
    'Master/Submaster Walkthrough (ECAM)': 'master_submaster_walkthrough_ecam',
    'Sequence Report Walkthrough (ECAM)': 'sequence_report_walkthrough_ecam',
    'Data Reprioritization/Retransmission Requests': 'data_reprioritization_retransmission_requests',
    'Notes to ECAM PDL': 'notes_to_ecam_pdl',
    'Summary PUL1': 'summary_pul1',
    'Summary PUL2': 'summary_pul2',
}

TOPIC_URL_TO_FUNC_NAME = {
    y : b for (a, b), (x, y) in zip(
        PAGE_TOPIC_FUNCTION_NAMES.items(), 
        PAGE_TOPIC_URL_STRINGS.items())
}
